
site_name: Yanic
site_description: Yet another node info collector - for respondd to be used with meshviewer to Grafana (with influxdb or graphite) 
site_author: FreifunkBremen
site_url: "https://freifunkbremen.github.io/yanic/"
repo_url: "https://github.com/FreifunkBremen/yanic"

remote_branch: gh-pages

docs_dir: docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/6204341
  font: false
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.indexes
    - navigation.sections
    - toc.integrate
    - toc.follow

    - content.action.edit

    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - offline
  - search:
      lang:
        - en
        - de

nav:
  - Home: index.md
  - About:  about.md
  - Running: running.md
  - Documentation:
      - Build and Install: docs/install.md
      - Usage: docs/usage.md
      - Quick Configuration: docs/quick_conf.md
      - Configuration: docs/configuration.md
  - Developing:
      - Database: dev/database.md
      - Output: dev/output.md
