when:
  - event: push
    branch: main

steps:
  - name: build
    image: codeberg.org/woodpecker-plugins/mkdocs:minimal

  - name: publish
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1
    settings:
      folder: site
      ssh_key:
        from_secret: DEPLOY_SSH_KEY
