when:
  - event: push
  - event: pull_request
  - event: tag
    ref: refs/tags/v*

clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      tags: true
      lfs: true


steps:
  - name: test
    image: golang
    depends_on: []
    commands:
      - make test

  - name: lint
    image: golangci/golangci-lint
    depends_on: []
    commands:
      - golangci-lint run -v ./...
      - golangci-lint fmt --diff-colored ./...

  - name: build
    image: golang
    depends_on: []
    environment:
      CGO: 0
      GOOS: linux
      GOARCH: amd64
    commands:
      - export FILENAME="yanic_$${GOARCH}_$${GOOS}"
      - go build -ldflags "-X github.com/FreifunkBremen/yanic/cmd.VERSION=$(git describe --tags)" -v -o "$${FILENAME}"
      - ./yanic_* version

  - name: container
    image: woodpeckerci/plugin-kaniko
    depends_on:
      - test
      - lint
      - build
    when:
      - event: push
        branch:
          - main
          - master
          - rc
      - event: tag
        ref: refs/tags/v*
    settings:
      dockerfile: Containerfile
      registry: "${CI_FORGE_URL#https://}"
      repo: "${CI_REPO,,}"
      auto_tag: true
      build_args:
        - VERSION=${CI_COMMIT_TAG:-${CI_COMMIT_SHA}}
      username: "${CI_REPO_OWNER}"
      password:
        from_secret: CODEBERG_TOKEN

  - name: release
    image: "docker.io/node"
    depends_on:
      - test
      - lint
      - build
    when:
      - event: push
        branch:
          - main
          - master
          - rc
    environment:
      GITEA_TOKEN:
        from_secret: CODEBERG_TOKEN
      GIT_CREDENTIALS:
        from_secret: CODEBERG_TOKEN
    commands:
      - export GITEA_URL="${CI_FORGE_URL}"
      - npm install semantic-release conventional-changelog-conventionalcommits @semantic-release/changelog @saithodev/semantic-release-gitea
      - "npx semantic-release"
